services:
  webhook-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gowa-webhook-api
    env_file:
      - .env
    expose:
      - "8000"
    restart: unless-stopped